"""
Configuration file for Python scripts.

Each SCRIPTS entry specifies a Python script that will be installed as cron job and
run in the specified docker container.

Contents are defined as follows:
    - args: The script's command line arguments | optional
    - cron: `cron` field definitions. See CRONTAB(5) man page. | required
    - docker_cmd: name of the DOCKER cmd configration that will run the script. See
        `config/docker`. If ommitted will use "default" DOCKER config | optional
    - enabled: If a cron script should installed for this script. If false or absent
        the entry will be ignored. | Optional
    - filename: The filename of the script. | reqiured
    - name: Text idenfier of the script. Will be used to name the cron shell script
        and *must be unique* to all script entries. | required
    - workdir: The path *relative to this repository* where the script is located. If
        omitted `docker run` will use the default working directory of the image | optional
    - comment: Optional comment which is ignored. | optional
"""

SCRIPTS = [
    {
        "cron": "# * * * * *",
        "docker_cmd": "test",
        "enabled": True,
        "name": "test",
        "workdir": "python-docker-cron/tests",
        "filename": "test.py",
        "comment" : "Used for testing. Can be removed."
    },
    {
        "cron": "50 2 * * *",
        "docker_cmd": "default",
        "enabled": True,
        "name": "backup",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "backup.py",
    },
    {
        "cron": "1 4 * * *",
        "enabled": True,
        "name": "bcycle_kiosks",
        "workdir": "transportation-data-publishing/transportation-data-publishing/bcycle",
        "filename": "bcycle_kiosk_pub.py",
    },
    {
        "cron": "3 4 * * 0",
        "enabled": True,
        "name": "bcycle_trips",
        "workdir": "transportation-data-publishing/transportation-data-publishing/bcycle",
        "filename": "bcycle_trip_pub.py",
    },
    {
        "args": ["cabinets", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "05 3 * * *",
        "enabled": True,
        "name": "cabinets",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["cameras", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "00 * * * *",
        "enabled": True,
        "name": "cameras",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "50 3 * * *",
        "enabled": True,
        "name": "detection_status_signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "detection_status_signals.py",
    },
    {
        "args": ["detectors", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "10 2 * * *",
        "enabled": True,
        "name": "detectors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["cameras", "data_tracker_prod", "--json"],
        "cron": "30 3 * * *",
        "enabled": True,
        "name": "device_status_cameras",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status.py",
    },
    {
        "args": ["detectors", "data_tracker_prod"],
        "cron": "40 3 * * *",
        "enabled": True,
        "name": "device_status_detectors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status.py",
    },
    {
        "args": ["gridsmart", "data_tracker_prod"],
        "cron": "45 3 * * *",
        "enabled": True,
        "name": "device_status_gridsmart",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status.py",
    },
    {
        "args": ["cameras", "data_tracker_prod"],
        "cron": "50 3 * * *",
        "enabled": True,
        "name": "device_status_log_cameras",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status_log.py",
    },
    {
        "args": ["gridsmart", "data_tracker_prod"],
        "cron": "56 3 * * *",
        "enabled": True,
        "name": "device_status_log_gridsmart",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status_log.py",
    },
    {
        "args": ["signals", "data_tracker_prod"],
        "cron": "52 3 * * *",
        "enabled": True,
        "name": "device_status_log_signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status_log.py",
    },
    {
        "args": ["travel_sensors", "data_tracker_prod"],
        "cron": "54 3 * * *",
        "enabled": True,
        "name": "device_status_log_travel_sensors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status_log.py",
    },
    {
        "args": ["signals", "data_tracker_prod"],
        "cron": "25 3 * * *",
        "enabled": True,
        "name": "device_status_signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status.py",
    },
    {
        "args": ["travel_sensors", "data_tracker_prod"],
        "cron": "35 3 * * *",
        "enabled": True,
        "name": "device_status_travel_sensors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "device_status.py",
    },
    {
        "args": ["dms", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "10 3 * * *",
        "enabled": True,
        "name": "dms",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "cron": "21 * * * *",
        "enabled": True,
        "name": "dms_msg_pub",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "dms_msg_pub.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "1-59/5 * * * *",
        "enabled": True,
        "name": "esb_xml_gen",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "esb_xml_gen.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "3-59/5 * * * *",
        "enabled": True,
        "name": "esb_xml_send",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "esb_xml_send.py",
    },
    {
        "args": ["hazard_flashers", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "15 3 * * *",
        "enabled": True,
        "name": "hazard_flashers",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "cron": "25 * * * *",
        "enabled": True,
        "name": "kits_cctv_push",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "kits_cctv_push.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "20 * * * *",
        "enabled": True,
        "name": "location_updater",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "location_updater.py",
    },
    {
        "args": ["pole_attachments", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "35 * * * *",
        "enabled": True,
        "name": "pole_attachments",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "cron": "5-59/15 * * * *",
        "enabled": True,
        "name": "radar_count_pub",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "radar_count_pub.py\n",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "25 2 * * *",
        "enabled": True,
        "name": "secondary_signals_updater",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "secondary_signals_updater.py",
    },
    {
        "cron": "*/2 * * * *",
        "enabled": True,
        "name": "sig_stat_pub",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "sig_stat_pub.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "20 2 * * *",
        "enabled": True,
        "name": "signal_pm_copier",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "signal_pm_copier.py",
    },
    {
        "args": ["phb", "data_tracker_prod"],
        "cron": "45 2 * * *",
        "enabled": True,
        "name": "signal_request_ranker_phb",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "signal_request_ranker.py",
    },
    {
        "args": ["traffic_signal", "data_tracker_prod"],
        "cron": "40 2 * * *",
        "enabled": True,
        "name": "signal_request_ranker_traffic_signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "signal_request_ranker.py",
    },
    {
        "args": ["signal_requests", "data_tracker_prod", "-d agol"],
        "cron": "40 * * * *",
        "enabled": True,
        "name": "signal_requests",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["signal_retiming", "data_tracker_prod", "-d socrata"],
        "cron": "30 * * * *",
        "enabled": True,
        "name": "signal_retiming",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["signals", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "15 * * * *",
        "enabled": True,
        "name": "signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "cron": "45 * * * *",
        "enabled": True,
        "name": "street_seg_updater",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "street_seg_updater.py",
    },
    {
        "args": ["timed_corridors", "data_tracker_prod", "-d socrata --replace"],
        "cron": "35 2 * * *",
        "enabled": True,
        "name": "timed_corridors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
        "comment": "Always replace this datastet because we don't know for certain when it was modified",
    },
    {
        "cron": "*/5 * * * *",
        "enabled": True,
        "name": "traffic_reports",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "traffic_reports.py",
    },
    {
        "args": ["traffic_reports", "data_tracker_prod", "-d socrata"],
        "cron": "6-59/5 * * * *",
        "enabled": True,
        "name": "traffic_reports_pub",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "pgrest_data_pub.py",
    },
    {
        "args": ["travel_sensors", "data_tracker_prod", "-d socrata", "-d agol"],
        "cron": "15 2 * * *",
        "enabled": True,
        "name": "travel_sensors",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["atd_visitor_log", "visitor_sign_in_prod", "-d socrata", "-d csv"],
        "cron": "00 2 * * *",
        "enabled": True,
        "name": "visitor_log",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["work_orders_signals", "data_tracker_prod", "-d socrata"],
        "cron": "50 * * * *",
        "enabled": True,
        "name": "work_orders_signals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "cron": "50 3 * * *",
        "enabled": True,
        "name": "traffic_study_locations",
        "workdir": "transportation-data-publishing/transportation-data-publishing/traffic_study",
        "filename": "traffic_study_locations.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "55 3 * * *",
        "enabled": True,
        "name": "tcp_business_days",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "tcp_business_days.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "04 4 * * *",
        "enabled": True,
        "name": "metadata_updater",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "metadata_updater.py",
    },
    {
        "args": ["data_tracker_prod"],
        "cron": "51 * * * *",
        "enabled": True,
        "name": "markings_agol",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "markings_agol.py",
    },
    {
        "cron": "07 */6 * * *",
        "enabled": True,
        "image": "atddocker/tdp",
        "name": "task_orders",
        "workdir": "transportation-data-publishing/transportation-data-publishing/data_tracker",
        "filename": "task_orders.py",
        "comment": "",
    },
    {
        "args": ["signal_request_evals", "data_tracker_prod", "-d socrata"],
        "cron": "37 * * * *",
        "enabled": True,
        "name": "signal_request_evals",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
    },
    {
        "args": ["signal_request_evals", "data_tracker_prod", "-d socrata", "--replace"],
        "cron": "4 * * * thu",
        "enabled": True,
        "name": "signal_request_evals_weekly",
        "workdir": "transportation-data-publishing/transportation-data-publishing/open_data",
        "filename": "knack_data_pub.py",
        "comment" : "This is a redundant weekly replace to act as a catch-all to make sure all signal request evals are updated."
    }
]
